### ISSUE TITLE
Replace copy/paste emoji images with a gem

### ISSUE THREAD

**Issue by kmcphillips** [ibawt/eightfoot#52]
Something like: https://github.com/github/gemoji

At the very least the images should be out of /public and into the asset pipeline.

**Comment by ibawt** [comment]
I thought we removed the emojis.  They were in there when we were show issue bodies but we took that out.

**Comment by ibawt** [comment]
we actually had gemoji in there at one point though.

**Comment by kmcphillips** [comment]
Ok cool. Well all the images are still in /public. Should I remove them?
